// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $about from "./routes/about.tsx";
import * as $api_films from "./routes/api/films.ts";
import * as $api_films_id_ from "./routes/api/films/[id].ts";
import * as $api_games from "./routes/api/games.ts";
import * as $api_games_id_ from "./routes/api/games/[id].ts";
import * as $api_series from "./routes/api/series.ts";
import * as $api_series_id_ from "./routes/api/series/[id].ts";
import * as $films from "./routes/films.tsx";
import * as $films_id_ from "./routes/films/[id].tsx";
import * as $games from "./routes/games.tsx";
import * as $games_id_ from "./routes/games/[id].tsx";
import * as $index from "./routes/index.tsx";
import * as $recruit from "./routes/recruit.tsx";
import * as $series from "./routes/series.tsx";
import * as $series_id_ from "./routes/series/[id].tsx";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/about.tsx": $about,
    "./routes/api/films.ts": $api_films,
    "./routes/api/films/[id].ts": $api_films_id_,
    "./routes/api/games.ts": $api_games,
    "./routes/api/games/[id].ts": $api_games_id_,
    "./routes/api/series.ts": $api_series,
    "./routes/api/series/[id].ts": $api_series_id_,
    "./routes/films.tsx": $films,
    "./routes/films/[id].tsx": $films_id_,
    "./routes/games.tsx": $games,
    "./routes/games/[id].tsx": $games_id_,
    "./routes/index.tsx": $index,
    "./routes/recruit.tsx": $recruit,
    "./routes/series.tsx": $series,
    "./routes/series/[id].tsx": $series_id_,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
